repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
- repo: https://github.com/openstack-dev/bashate
  rev: master
  hooks:
  - id: bashate
    args: [ -i, E006 ]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.0
  hooks:
  - id: shellcheck
